# Generated by Django 6.0.4 on 2026-04-16 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rentals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Tên nhà cung cấp"),
                ),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                ("email", models.EmailField(max_length=255, verbose_name="Email")),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="Địa chỉ"),
                ),
            ],
            options={
                "verbose_name": "Nhà cung cấp",
                "verbose_name_plural": "Danh sách Nhà cung cấp",
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên địa điểm")),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Địa chỉ chi tiết"
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Vĩ độ",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=10,
                        null=True,
                        verbose_name="Kinh độ",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sub_locations",
                        to="rentals.location",
                        verbose_name="Trực thuộc",
                    ),
                ),
            ],
            options={
                "verbose_name": "Địa điểm",
                "verbose_name_plural": "Danh sách Địa điểm",
            },
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Tên xe")),
                ("brand", models.CharField(max_length=255, verbose_name="Hãng xe")),
                ("type", models.CharField(max_length=100, verbose_name="Loại xe")),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Giá cơ bản/Ngày"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Sẵn sàng"),
                            ("rented", "Đang cho thuê"),
                            ("maintenance", "Bảo dưỡng"),
                        ],
                        default="available",
                        max_length=50,
                        verbose_name="Tình trạng",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Mô tả chi tiết"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="cars/",
                        verbose_name="Hình ảnh xe",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cars",
                        to="rentals.location",
                        verbose_name="Địa điểm hiện tại",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="rentals.supplier",
                        verbose_name="Nhà cung cấp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xe",
                "verbose_name_plural": "Danh sách Xe",
            },
        ),
    ]
